// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82805ebdf0b5ff0d "Apptics (copy)", do not edit manually */
"use client";

// virtual:section/partners
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ArbboFPMCpMjiOI7DT8q/AV2TpZp27bcMBLjrNaOo/oGYuuM1R2.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/bSG2fUXcc43766cbIglD/Ticker.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	Children,
	useLayoutEffect,
	useEffect,
	useState,
	useRef,
	useMemo,
	useCallback,
	cloneElement,
} from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	useReducedMotion,
	LayoutGroup,
	useInView,
	useMotionValue,
	useTransform,
	motion,
	frame,
} from "unframer";
import { resize } from "@motionone/dom";
var MAX_DUPLICATED_ITEMS = 100;
var directionTransformers = {
	left: (offset) => `translateX(-${offset}px)`,
	right: (offset) => `translateX(${offset}px)`,
	top: (offset) => `translateY(-${offset}px)`,
	bottom: (offset) => `translateY(${offset}px)`,
};
function Ticker(props) {
	let {
		slots = [],
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		speed,
		hoverFactor,
		direction,
		alignment,
		sizingOptions,
		fadeOptions,
		style,
	} = props;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const { widthType, heightType } = sizingOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const currentTarget = RenderTarget.current();
	const isCanvas =
		currentTarget === RenderTarget.canvas ||
		currentTarget === RenderTarget.export;
	const filteredSlots = slots.filter(Boolean);
	const numChildren = Children.count(filteredSlots);
	const hasChildren = numChildren > 0;
	if (direction === true) {
		direction = "left";
	}
	const isHorizontal = direction === "left" || direction === "right";
	const offset = useMotionValue(0);
	const transformer = directionTransformers[direction];
	const transform = useTransform(offset, transformer);
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, []);
	const [size, setSize] = useState({
		parent: null,
		children: null,
	});
	let clonedChildren = null;
	let dupedChildren = [];
	let duplicateBy = 0;
	let opacity = 0;
	if (isCanvas) {
		duplicateBy = numChildren ? Math.floor(10 / numChildren) : 0;
		opacity = 1;
	}
	if (!isCanvas && hasChildren && size.parent) {
		duplicateBy = Math.round((size.parent / size.children) * 2) + 1;
		duplicateBy = Math.min(duplicateBy, MAX_DUPLICATED_ITEMS);
		opacity = 1;
	}
	const measure = useCallback(() => {
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = childrenRef[0].current
				? isHorizontal
					? childrenRef[0].current.offsetLeft
					: childrenRef[0].current.offsetTop
				: 0;
			const end = childrenRef[1].current
				? isHorizontal
					? childrenRef[1].current.offsetLeft +
						childrenRef[1].current.offsetWidth
					: childrenRef[1].current.offsetTop +
						childrenRef[1].current.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			setSize({
				parent: parentLength,
				children: childrenLength,
			});
		}
	}, []);
	const childrenStyles = isCanvas
		? {
				contentVisibility: "auto",
			}
		: {};
	if (hasChildren) {
		if (!isCanvas) {
			let initialResize = useRef(true);
			useLayoutEffect(() => {
				frame.read(measure, false, true);
				return resize(parentRef.current, ({ contentSize }) => {
					if (
						!initialResize.current &&
						(contentSize.width || contentSize.height)
					) {
						frame.read(measure, false, true);
					}
					initialResize.current = false;
				});
			}, []);
		}
		clonedChildren = Children.map(filteredSlots, (child, index) => {
			let ref;
			if (index === 0) {
				ref = childrenRef[0];
			}
			if (index === filteredSlots.length - 1) {
				ref = childrenRef[1];
			}
			const size2 = {
				width: widthType ? child.props?.width : "100%",
				height: heightType ? child.props?.height : "100%",
			};
			return (
				<LayoutGroup inherit={"id"}>
					<li ref={ref} style={size2}>
						{
							/* @__PURE__ */ cloneElement(
								child,
								{
									style: {
										...child.props?.style,
										...size2,
										flexShrink: 0,
										...childrenStyles,
									},
									layoutId: child.props.layoutId
										? child.props.layoutId + "-original-" + index
										: void 0,
								},
								child.props?.children,
							)
						}
					</li>
				</LayoutGroup>
			);
		});
	}
	const isInView = isCanvas ? true : useInView(parentRef);
	if (!isCanvas) {
		for (let i = 0; i < duplicateBy; i++) {
			dupedChildren = dupedChildren.concat(
				Children.map(filteredSlots, (child, childIndex) => {
					const size2 = {
						width: widthType ? child.props?.width : "100%",
						height: heightType ? child.props?.height : "100%",
						willChange: !isInView ? void 0 : "transform",
					};
					return (
						<LayoutGroup inherit={"id"}>
							<li style={size2} aria-hidden={true}>
								{
									/* @__PURE__ */ cloneElement(
										child,
										{
											key: i + " " + childIndex,
											style: {
												...child.props?.style,
												width: widthType ? child.props?.width : "100%",
												height: heightType ? child.props?.height : "100%",
												flexShrink: 0,
												...childrenStyles,
											},
											layoutId: child.props.layoutId
												? child.props.layoutId + "-dupe-" + i
												: void 0,
										},
										child.props?.children,
									)
								}
							</li>
						</LayoutGroup>
					);
				}),
			);
		}
	}
	const animateToValue =
		size.children + size.children * Math.round(size.parent / size.children);
	const initialTime = useRef(null);
	const prevTime = useRef(null);
	const xOrY = useRef(0);
	const isHover = useRef(false);
	const isReducedMotion = useReducedMotion();
	const listRef = useRef(null);
	const animationRef = useRef(null);
	if (!isCanvas) {
		useEffect(() => {
			if (isReducedMotion || !animateToValue || !speed) {
				return;
			}
			animationRef.current = listRef.current.animate(
				{
					transform: [transformer(0), transformer(animateToValue)],
				},
				{
					duration: (Math.abs(animateToValue) / speed) * 1e3,
					iterations: Infinity,
					easing: "linear",
				},
			);
			return () => animationRef.current.cancel();
		}, [hoverFactor, animateToValue, speed]);
		const playOrPause = useCallback(() => {
			if (!animationRef.current) return;
			const hidden = document.hidden;
			if (isInView && !hidden && animationRef.current.playState === "paused") {
				animationRef.current.play();
			} else if (
				(!isInView || hidden) &&
				animationRef.current.playState === "running"
			) {
				animationRef.current.pause();
			}
		}, [isInView]);
		useEffect(() => {
			playOrPause();
		}, [isInView, hoverFactor, animateToValue, speed]);
		useEffect(() => {
			document.addEventListener("visibilitychange", playOrPause);
			return () => {
				document.removeEventListener("visibilitychange", playOrPause);
			};
		}, [playOrPause]);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2728"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to infinitely loop on your page."}
				</p>
			</section>
		);
	}
	return (
		<section
			style={{
				...containerStyle,
				opacity,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				overflow: overflow ? "visible" : "hidden",
				padding: paddingValue,
			}}
			ref={parentRef}
		>
			<motion.ul
				ref={listRef}
				style={{
					...containerStyle,
					gap,
					top:
						direction === "bottom" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					left:
						direction === "right" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					placeItems: alignment,
					position: "relative",
					flexDirection: isHorizontal ? "row" : "column",
					...style,
					willChange: isCanvas || !isInView ? "auto" : "transform",
					transform: transformer(0),
				}}
				onMouseEnter={() => {
					isHover.current = true;
					if (animationRef.current) {
						animationRef.current.playbackRate = hoverFactor;
					}
				}}
				onMouseLeave={() => {
					isHover.current = false;
					if (animationRef.current) {
						animationRef.current.playbackRate = 1;
					}
				}}
			>
				{clonedChildren}
				{dupedChildren}
			</motion.ul>
		</section>
	);
}
Ticker.defaultProps = {
	gap: 10,
	padding: 10,
	sizingOptions: {
		widthType: true,
		heightType: true,
	},
	fadeOptions: {
		fadeContent: true,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	direction: true,
};
addPropertyControls(Ticker, {
	slots: {
		type: ControlType.Array,
		title: "Children",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	speed: {
		type: ControlType.Number,
		title: "Speed",
		min: 0,
		max: 1e3,
		defaultValue: 100,
		unit: "%",
		displayStepper: true,
		step: 5,
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	sizingOptions: {
		type: ControlType.Object,
		title: "Sizing",
		controls: {
			widthType: {
				type: ControlType.Boolean,
				title: "Width",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
			heightType: {
				type: ControlType.Boolean,
				title: "Height",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
		},
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: true,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	hoverFactor: {
		type: ControlType.Number,
		title: "Hover",
		min: 0,
		max: 1,
		unit: "x",
		defaultValue: 1,
		step: 0.1,
		displayStepper: true,
		description: "Slows down the speed while you are hovering.",
	},
});
var containerStyle = {
	display: "flex",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 150,
	lineHeight: 1.5,
	textAlign: "center",
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var isValidNumber = (value) => typeof value === "number" && !isNaN(value);

// /:https://framerusercontent.com/modules/z0X9SUuoy0PBGuJZjUgA/QP97eJvdkh7aerUm9jMh/DqPpqUUr0.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-SemiBold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	'.framer-Mkvj4 .framer-styles-preset-c1cxty:not(.rich-text-wrapper), .framer-Mkvj4 .framer-styles-preset-c1cxty.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 140%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-94158dc5-efda-4690-8a29-fea011c5c81e, #7d7e80); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-Mkvj4 .framer-styles-preset-c1cxty:not(.rich-text-wrapper), .framer-Mkvj4 .framer-styles-preset-c1cxty.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 140%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-94158dc5-efda-4690-8a29-fea011c5c81e, #7d7e80); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-Mkvj4 .framer-styles-preset-c1cxty:not(.rich-text-wrapper), .framer-Mkvj4 .framer-styles-preset-c1cxty.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 600; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 140%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-94158dc5-efda-4690-8a29-fea011c5c81e, #7d7e80); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-Mkvj4";

// /:https://framerusercontent.com/modules/ArbboFPMCpMjiOI7DT8q/AV2TpZp27bcMBLjrNaOo/oGYuuM1R2.js
var TickerFonts = getFonts(Ticker);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder = ["vCpQijkMR", "Xg06KIpM0", "DoQOLvLO5"];
var serializationHash = "framer-IKNA8";
var variantClassNames = {
	DoQOLvLO5: "framer-v-3o18jy",
	vCpQijkMR: "framer-v-txuafi",
	Xg06KIpM0: "framer-v-12rwsuk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0.22, 0.61, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 60,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "vCpQijkMR",
	Phone: "DoQOLvLO5",
	Tablet: "Xg06KIpM0",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "vCpQijkMR",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "vCpQijkMR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["Xg06KIpM0", "DoQOLvLO5"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (["Xg06KIpM0", "DoQOLvLO5"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-txuafi",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"vCpQijkMR"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								DoQOLvLO5: {
									"data-framer-name": "Phone",
								},
								Xg06KIpM0: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-euchpx"}
							layoutDependency={layoutDependency}
							layoutId={"ktB8KUFiE"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-19x52hd"}
								data-framer-name={
									"\xA0Seamless Integration Across all your Apps"
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"qloM9s47d"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-ad43a539-e7dd-4526-9939-6d192077376e, rgb(36, 36, 36))",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion2.p
										className={"framer-styles-preset-c1cxty"}
										data-styles-preset={"DqPpqUUr0"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-ad43a539-e7dd-4526-9939-6d192077376e, rgb(36, 36, 36)))",
										}}
									>
										{"Seamless Integration Across All Your Apps"}
									</motion2.p>
								</React.Fragment>
							</RichText>
						</motion2.div>
						{isDisplayed() && (
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-cimvsy-container"}
									data-framer-name={"Desktop"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"w8P3zaqxj-container"}
									name={"Desktop"}
									nodeId={"w8P3zaqxj"}
									rendersWithMotion={true}
									scopeId={"oGYuuM1R2"}
								>
									<Ticker
										alignment={"center"}
										direction={"left"}
										fadeOptions={{
											fadeAlpha: 0,
											fadeContent: true,
											fadeInset: 0,
											fadeWidth: 25,
											overflow: false,
										}}
										gap={60}
										height={"100%"}
										hoverFactor={1}
										id={"w8P3zaqxj"}
										layoutId={"w8P3zaqxj"}
										name={"Desktop"}
										padding={10}
										paddingBottom={10}
										paddingLeft={10}
										paddingPerSide={false}
										paddingRight={10}
										paddingTop={10}
										sizingOptions={{
											heightType: true,
											widthType: true,
										}}
										slots={[
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 36,
													intrinsicWidth: 277.5,
													pixelHeight: 72,
													pixelWidth: 555,
													sizes: "246.6667px",
													src: "https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png?scale-down-to=512 512w,https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png 555w",
												}}
												className={"framer-1a4tivo"}
												data-framer-name={"Checkoutcom logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"Xu_xL8mtQ"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 70,
													intrinsicWidth: 276.5,
													pixelHeight: 140,
													pixelWidth: 553,
													sizes: "244.9px",
													src: "https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png?scale-down-to=512 512w,https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png 553w",
												}}
												className={"framer-13m4wot"}
												data-framer-name={"Bigcommerce logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"COIUWTZV3"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 55.5,
													intrinsicWidth: 258.5,
													pixelHeight: 111,
													pixelWidth: 517,
													sizes: "228.2252px",
													src: "https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png?scale-down-to=512 512w,https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png 517w",
												}}
												className={"framer-1htd18u"}
												data-framer-name={"Wordpresscom logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"wJ4mW7yzb"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 51,
													intrinsicWidth: 195,
													pixelHeight: 102,
													pixelWidth: 390,
													src: "https://framerusercontent.com/images/YDinNZ7NdWrd0yO9bXdKTmug4BI.png",
												}}
												className={"framer-tid78a"}
												data-framer-name={"Logo Alternative.svg"}
												layoutDependency={layoutDependency}
												layoutId={"tKvLffp_H"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 49,
													intrinsicWidth: 171.5,
													pixelHeight: 98,
													pixelWidth: 343,
													src: "https://framerusercontent.com/images/QQ4cQSlsWAeKFCywpLVHtUOZZY.png",
												}}
												className={"framer-1gd09qu"}
												data-framer-name={"Logo.svg-1"}
												layoutDependency={layoutDependency}
												layoutId={"gIm9rCD0C"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 80,
													intrinsicWidth: 168,
													pixelHeight: 160,
													pixelWidth: 336,
													src: "https://framerusercontent.com/images/HzVqNuiqUU63rr24PItciadTL34.png",
												}}
												className={"framer-106lvst"}
												data-framer-name={"Logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"dcJVdT7gF"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 46,
													intrinsicWidth: 144.5,
													pixelHeight: 92,
													pixelWidth: 289,
													src: "https://framerusercontent.com/images/G1gqNw6Q3b3a1iQlqEKuQ3mX5pk.png",
												}}
												className={"framer-1vtonni"}
												data-framer-name={"Nmi logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"Q3q1Ybgeo"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 32,
													intrinsicWidth: 123.5,
													pixelHeight: 64,
													pixelWidth: 247,
													src: "https://framerusercontent.com/images/6oGyMrlS7OpCbcz3iHrVleYyFYo.png",
												}}
												className={"framer-105hhgk"}
												data-framer-name={"Logo.svg-2"}
												layoutDependency={layoutDependency}
												layoutId={"rJpLrnKHj"}
											/>,
										]}
										speed={80}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed1() && (
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1wqm6yx-container"}
									data-framer-name={"Tab and mob"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"iBUlUZFT4-container"}
									name={"Tab and mob"}
									nodeId={"iBUlUZFT4"}
									rendersWithMotion={true}
									scopeId={"oGYuuM1R2"}
								>
									<Ticker
										alignment={"center"}
										direction={"left"}
										fadeOptions={{
											fadeAlpha: 0,
											fadeContent: true,
											fadeInset: 0,
											fadeWidth: 25,
											overflow: false,
										}}
										gap={20}
										height={"100%"}
										hoverFactor={1}
										id={"iBUlUZFT4"}
										layoutId={"iBUlUZFT4"}
										name={"Tab and mob"}
										padding={10}
										paddingBottom={10}
										paddingLeft={10}
										paddingPerSide={false}
										paddingRight={10}
										paddingTop={10}
										sizingOptions={{
											heightType: true,
											widthType: true,
										}}
										slots={[
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 36,
													intrinsicWidth: 277.5,
													pixelHeight: 72,
													pixelWidth: 555,
													sizes: "192.7083px",
													src: "https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png?scale-down-to=512 512w,https://framerusercontent.com/images/dVjD0t492YB9FvnC5K3hFJf3zw.png 555w",
												}}
												className={"framer-1bnrhnx"}
												data-framer-name={"Checkoutcom logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"SOaly_tJm"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 70,
													intrinsicWidth: 276.5,
													pixelHeight: 140,
													pixelWidth: 553,
													sizes: "158px",
													src: "https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png?scale-down-to=512 512w,https://framerusercontent.com/images/ogZybme8zuR2VTVNfOwK7j5mP0.png 553w",
												}}
												className={"framer-1xncqu4"}
												data-framer-name={"Bigcommerce logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"ggQs3AOQR"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 55.5,
													intrinsicWidth: 258.5,
													pixelHeight: 111,
													pixelWidth: 517,
													sizes: "163.018px",
													src: "https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png?scale-down-to=512",
													srcSet:
														"https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png?scale-down-to=512 512w,https://framerusercontent.com/images/ebFoGTqsfoLDTD1lPUYprWeduw.png 517w",
												}}
												className={"framer-1oi9i3m"}
												data-framer-name={"Wordpresscom logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"mK5jJvnzd"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 51,
													intrinsicWidth: 195,
													pixelHeight: 102,
													pixelWidth: 390,
													src: "https://framerusercontent.com/images/YDinNZ7NdWrd0yO9bXdKTmug4BI.png",
												}}
												className={"framer-odm95r"}
												data-framer-name={"Logo Alternative.svg"}
												layoutDependency={layoutDependency}
												layoutId={"RPSsWtj6e"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 49,
													intrinsicWidth: 171.5,
													pixelHeight: 98,
													pixelWidth: 343,
													src: "https://framerusercontent.com/images/QQ4cQSlsWAeKFCywpLVHtUOZZY.png",
												}}
												className={"framer-fre352"}
												data-framer-name={"Logo.svg-1"}
												layoutDependency={layoutDependency}
												layoutId={"BabJQTOMI"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 80,
													intrinsicWidth: 168,
													pixelHeight: 160,
													pixelWidth: 336,
													src: "https://framerusercontent.com/images/HzVqNuiqUU63rr24PItciadTL34.png",
												}}
												className={"framer-19ertjq"}
												data-framer-name={"Logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"CPXRZv4Bv"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 46,
													intrinsicWidth: 144.5,
													pixelHeight: 92,
													pixelWidth: 289,
													src: "https://framerusercontent.com/images/G1gqNw6Q3b3a1iQlqEKuQ3mX5pk.png",
												}}
												className={"framer-tqaj6o"}
												data-framer-name={"Nmi logo.svg"}
												layoutDependency={layoutDependency}
												layoutId={"yIGhlLYIq"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 32,
													intrinsicWidth: 123.5,
													pixelHeight: 64,
													pixelWidth: 247,
													src: "https://framerusercontent.com/images/6oGyMrlS7OpCbcz3iHrVleYyFYo.png",
												}}
												className={"framer-9rept6"}
												data-framer-name={"Logo.svg-2"}
												layoutDependency={layoutDependency}
												layoutId={"L4ZFKpO26"}
											/>,
										]}
										speed={80}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IKNA8.framer-12vgepp, .framer-IKNA8 .framer-12vgepp { display: block; }",
	".framer-IKNA8.framer-txuafi { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 40px 0px 40px 0px; position: relative; width: 1200px; }",
	".framer-IKNA8 .framer-euchpx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-IKNA8 .framer-19x52hd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-IKNA8 .framer-cimvsy-container, .framer-IKNA8 .framer-1wqm6yx-container { flex: none; height: 66px; position: relative; width: 100%; }",
	".framer-IKNA8 .framer-1a4tivo { aspect-ratio: 7.708333333333333 / 1; height: var(--framer-aspect-ratio-supported, 32px); overflow: visible; position: relative; width: 246px; }",
	".framer-IKNA8 .framer-13m4wot { aspect-ratio: 3.95 / 1; height: var(--framer-aspect-ratio-supported, 62px); overflow: visible; position: relative; width: 245px; }",
	".framer-IKNA8 .framer-1htd18u { aspect-ratio: 4.657657657657658 / 1; height: var(--framer-aspect-ratio-supported, 49px); overflow: visible; position: relative; width: 229px; }",
	".framer-IKNA8 .framer-tid78a { aspect-ratio: 3.823529411764706 / 1; height: var(--framer-aspect-ratio-supported, 45px); overflow: visible; position: relative; width: 172px; }",
	".framer-IKNA8 .framer-1gd09qu { aspect-ratio: 3.5 / 1; height: var(--framer-aspect-ratio-supported, 43px); overflow: visible; position: relative; width: 152px; }",
	".framer-IKNA8 .framer-106lvst { aspect-ratio: 2.1 / 1; height: var(--framer-aspect-ratio-supported, 64px); overflow: visible; position: relative; width: 134px; }",
	".framer-IKNA8 .framer-1vtonni { aspect-ratio: 3.141304347826087 / 1; height: var(--framer-aspect-ratio-supported, 41px); overflow: visible; position: relative; width: 128px; }",
	".framer-IKNA8 .framer-105hhgk { aspect-ratio: 3.859375 / 1; height: var(--framer-aspect-ratio-supported, 28px); overflow: visible; position: relative; width: 110px; }",
	".framer-IKNA8 .framer-1bnrhnx { aspect-ratio: 7.708333333333333 / 1; height: var(--framer-aspect-ratio-supported, 25px); overflow: visible; position: relative; width: 191px; }",
	".framer-IKNA8 .framer-1xncqu4 { aspect-ratio: 3.95 / 1; height: var(--framer-aspect-ratio-supported, 40px); overflow: visible; position: relative; width: 157px; }",
	".framer-IKNA8 .framer-1oi9i3m { aspect-ratio: 4.657657657657658 / 1; height: var(--framer-aspect-ratio-supported, 35px); overflow: visible; position: relative; width: 165px; }",
	".framer-IKNA8 .framer-odm95r { aspect-ratio: 3.823529411764706 / 1; height: var(--framer-aspect-ratio-supported, 29px); overflow: visible; position: relative; width: 112px; }",
	".framer-IKNA8 .framer-fre352 { aspect-ratio: 3.5 / 1; height: var(--framer-aspect-ratio-supported, 28px); overflow: visible; position: relative; width: 99px; }",
	".framer-IKNA8 .framer-19ertjq { aspect-ratio: 2.1 / 1; height: var(--framer-aspect-ratio-supported, 42px); overflow: visible; position: relative; width: 89px; }",
	".framer-IKNA8 .framer-tqaj6o { aspect-ratio: 3.141304347826087 / 1; height: var(--framer-aspect-ratio-supported, 34px); overflow: visible; position: relative; width: 106px; }",
	".framer-IKNA8 .framer-9rept6 { aspect-ratio: 3.859375 / 1; height: var(--framer-aspect-ratio-supported, 22px); overflow: visible; position: relative; width: 85px; }",
	".framer-IKNA8.framer-v-12rwsuk.framer-txuafi { width: 810px; }",
	".framer-IKNA8.framer-v-3o18jy.framer-txuafi { gap: 20px; width: 390px; }",
	".framer-IKNA8.framer-v-3o18jy .framer-19x52hd { --framer-text-wrap-override: balance; }",
	...css,
];
var FrameroGYuuM1R2 = withCSS(Component, css2, "framer-IKNA8");
var stdin_default = FrameroGYuuM1R2;
FrameroGYuuM1R2.displayName = "Section/Partners";
FrameroGYuuM1R2.defaultProps = {
	height: 204,
	width: 1200,
};
addPropertyControls2(FrameroGYuuM1R2, {
	variant: {
		options: ["vCpQijkMR", "Xg06KIpM0", "DoQOLvLO5"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FrameroGYuuM1R2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TickerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section/partners
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	XZOGP48SF: {
		path: "/sakljflasdf",
	},
	augiA20Il: {
		path: "/",
	},
};

// virtual:section/partners
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82805ebdf0b5ff0d009fec4f748e6f81207f7e9b7f138594ce37e1d247ff0150"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PartnersFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82805ebdf0b5ff0d009fec4f748e6f81207f7e9b7f138594ce37e1d247ff0150"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var partners_default = ComponentWithRoot;
export { partners_default as default };
